import re

path = r'c:\Users\kmura\backend\alembic\versions\20260812_1858_66a422e96f8f_phase_3_add_sos_report_model.py'
with open(path, 'r') as f:
    content = f.read()

new_upgrade = """def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sos_report',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('is_quick_sos', sa.Boolean(), nullable=False),
    sa.Column('emergency_type', sa.String(), nullable=False),
    sa.Column('severity_hint', sa.String(), nullable=True),
    sa.Column('people_count', sa.Integer(), nullable=True),
    sa.Column('medical_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_message', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('relay_hop_count', sa.Integer(), nullable=False),
    sa.Column('last_relayed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cluster_id', sa.String(), nullable=True),
    sa.Column('received_via_gateway_device_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_sos_report_location', 'sos_report', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_sos_report_cluster_id'), 'sos_report', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_sos_report_device_id'), 'sos_report', ['device_id'], unique=False)
    op.create_index(op.f('ix_sos_report_uuid'), 'sos_report', ['uuid'], unique=False)
    # ### end Alembic commands ###"""

new_downgrade = """def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sos_report_uuid'), table_name='sos_report')
    op.drop_index(op.f('ix_sos_report_device_id'), table_name='sos_report')
    op.drop_index(op.f('ix_sos_report_cluster_id'), table_name='sos_report')
    op.drop_index('idx_sos_report_location', table_name='sos_report', postgresql_using='gist')
    op.drop_table('sos_report')
    # ### end Alembic commands ###"""

header = content.split('def upgrade() -> None:')[0]

new_content = header + new_upgrade + '\n\n\n' + new_downgrade + '\n'

with open(path, 'w') as f:
    f.write(new_content)
print('Done!')
