"""Initial schema

Revision ID: 04fe9120f497
Revises: 
Create Date: 2026-08-13 18:39:31.105641+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04fe9120f497'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis;')
    op.create_table('authority',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('agency', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authority_email'), 'authority', ['email'], unique=True)
    op.create_table('device',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_model', sa.String(), nullable=False),
    sa.Column('app_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('cluster_id', sa.String(), nullable=False),
    sa.Column('source_sos_uuids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('area_name', sa.String(), nullable=True),
    sa.Column('emergency_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('ai_summary', sa.String(), nullable=True),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('estimated_people_affected', sa.Integer(), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('recommended_resources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assigned_resources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_index(op.f('ix_incident_cluster_id'), 'incident', ['cluster_id'], unique=True)
    op.create_index(op.f('ix_incident_incident_id'), 'incident', ['incident_id'], unique=False)
    op.create_table('resource',
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('sub_type', sa.String(), nullable=False),
    sa.Column('custodian_agency', sa.String(), nullable=False),
    sa.Column('quantity_total', sa.Integer(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity_available >= 0', name='check_quantity_available_positive'),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index(op.f('ix_resource_category'), 'resource', ['category'], unique=False)
    op.create_index(op.f('ix_resource_district'), 'resource', ['district'], unique=False)
    op.create_index(op.f('ix_resource_resource_id'), 'resource', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_status'), 'resource', ['status'], unique=False)
    op.create_table('sos_report',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('is_quick_sos', sa.Boolean(), nullable=False),
    sa.Column('emergency_type', sa.String(), nullable=False),
    sa.Column('severity_hint', sa.String(), nullable=True),
    sa.Column('people_count', sa.Integer(), nullable=True),
    sa.Column('medical_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_message', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('relay_hop_count', sa.Integer(), nullable=False),
    sa.Column('last_relayed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cluster_id', sa.String(), nullable=True),
    sa.Column('received_via_gateway_device_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_sos_report_cluster_id'), 'sos_report', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_sos_report_device_id'), 'sos_report', ['device_id'], unique=False)
    op.create_index(op.f('ix_sos_report_uuid'), 'sos_report', ['uuid'], unique=False)
    op.create_table('dispatch_record',
    sa.Column('dispatch_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('quantity_dispatched', sa.Integer(), nullable=False),
    sa.Column('dispatched_by', sa.String(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eta_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.incident_id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.resource_id'], ),
    sa.PrimaryKeyConstraint('dispatch_id')
    )
    op.create_index(op.f('ix_dispatch_record_dispatch_id'), 'dispatch_record', ['dispatch_id'], unique=False)
    op.create_index(op.f('ix_dispatch_record_incident_id'), 'dispatch_record', ['incident_id'], unique=False)
    op.create_index(op.f('ix_dispatch_record_resource_id'), 'dispatch_record', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispatch_record_resource_id'), table_name='dispatch_record')
    op.drop_index(op.f('ix_dispatch_record_incident_id'), table_name='dispatch_record')
    op.drop_index(op.f('ix_dispatch_record_dispatch_id'), table_name='dispatch_record')
    op.drop_table('dispatch_record')
    op.drop_index(op.f('ix_sos_report_uuid'), table_name='sos_report')
    op.drop_index(op.f('ix_sos_report_device_id'), table_name='sos_report')
    op.drop_index(op.f('ix_sos_report_cluster_id'), table_name='sos_report')
    op.drop_table('sos_report')
    op.drop_index(op.f('ix_resource_status'), table_name='resource')
    op.drop_index(op.f('ix_resource_resource_id'), table_name='resource')
    op.drop_index(op.f('ix_resource_district'), table_name='resource')
    op.drop_index(op.f('ix_resource_category'), table_name='resource')
    op.drop_table('resource')
    op.drop_index(op.f('ix_incident_incident_id'), table_name='incident')
    op.drop_index(op.f('ix_incident_cluster_id'), table_name='incident')
    op.drop_table('incident')
    op.drop_table('device')
    op.drop_index(op.f('ix_authority_email'), table_name='authority')
    op.drop_table('authority')
    op.execute('DROP EXTENSION IF EXISTS postgis;')
    # ### end Alembic commands ###
